# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
INHERIT: docs/base.yml  # use the shared AutoRA configuration by default

site_name: AutoRA DARTS Theorist
repo_url: 'https://github.com/autoresearch/autora-darts'

#plugins:
#  multirepo:
#    imported_repo: true
#    url: file://Users/`jholla10/Developer/autora
#    section_name: DARTS
#    # dirs/files needed for building the site
#    # any path in docs will be included. For example, index.md is the
#    # homepage of the parent site
#    paths: ["mkdocs/*", "mkdocs.yml", "docs/*"]
#    custom_dir: mkdocs
#    yml_file: mkdocs.yml # this can also be a relative path
#    branch: main


nav:
- Introduction: 'index.md'
- Quickstart: "quickstart.md"
- How it works: 'how_it_works.md'
- Meta parameters: 'meta_parameters.md'
- Search space: 'search_space.md'
- Examples:
  - Basic Usage: 'example.ipynb'
#  - Weber-Fechner Law: 'weber.ipynb'
- Code Reference: reference/
